version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/shop
    depends_on:
      - mongo
    command: >
      sh -c "npm run migration:up && npm start"

  mongo:
    image: mongo
    ports:
      - "27017:27017"